---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: test  
  labels:
    name: postgres
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
      type: service
  template:
    metadata:
      labels:
        name: postgres
        type: service
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: secret
          volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
            subPath: postgres #Add subPath            
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: test  
  labels:
    name: postgres
    type: api
spec:
  selector:
    name: postgres
    type: service
  ports:
  - port: 5432
    name: postgres-api
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: test  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M